version: '3.8'

networks:
  network-ctrl-auth-api:
    driver: bridge

services:

  api-auth:
    image: rafaelbrunof/service-auth-api
    networks:
      - network-ctrl-auth-api
    depends_on:
      - mongo
      - redis
    ports:
      - "8080:8080"
    env_file:
      - ./.env

  mongo:
    image: mongo:latest
    container_name: mongo
    networks:
      - network-ctrl-auth-api
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE_NAME}
    env_file:
      - ./.env
    volumes:
      - mongo:/data/db
    ports:
      - '6000:27017'

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - network-ctrl-auth-api
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

volumes:
  mongo:
  redis: