version: '3.8'

services:

  mongo:
    image: mongo:latest
    container_name: mongo-monitor-integrations
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - '6001:27017'